### ISSUE TITLE
[v0.8.6][Integration] Implement simulated orbit information

### ISSUE THREAD

**Issue by yuyuqq** [space-station-os/space_station_os#57]
## User Story:
- Identifying parameteres for orbit design abstraction.
- For implementation of demo_sarj_power_generation, verious orbit information is needed.
- Bringing it to the Integration

## Acceptance Criteria:
- Set abstraction parameters for different orbits
- Simulate orbit dynamics 
- Display it on ground station
- Implement in the Integration
- Prepare for README

**Comment by k-suga-SD** [comment]
- Set abstraction parameters for different orbits: by 2025/4/21
- Simulate orbit dynamics
  - Implement time integration method: by 2025/5/5
  - Consider J2 term: by 2025/4/21
  - Consider air drag: by 2025/4/28
  - Consider solar radiation: by 2025/5/5
- Display it on ground station: by 2025/5/19
- Implement in the Integration: by 2025/6/2
- Prepare for README: at any time

**Comment by k-suga-SD** [comment]
Until now, I have implemented simulations of attitude and orbital dynamics as demos. Of these, I will integrate the orbital dynamics into the main body of the space station OS (the attitude dynamics have already been implemented in space_station_gnc).

## Policy:
- Use attitude data published in "space_station_gnc/src/physics_motion.cpp"

## My task:
- understand "space_station_gnc/src/thruster_matrix.cpp" because thruster matrix data is required to simulate orbit dynamics
  - Make readme
  - include this file
- understand "space_station_gnc/src/physics_motion.cpp" because attitude dynamics is implemented in this file
  - make readme
  - use topics in it

## unclear points
- Thruster assign matrix
- Thruster force
- thruster uncertainty model
- Mass property of space station (total mass, inertia tensor and center of mass)

**Comment by k-suga-SD** [comment]
working branch is https://github.com/k-suga-SD/space_station_os_orbit/tree/v0.8.5-feature/57-orbit

**Comment by k-suga-SD** [comment]
I made PR.
I have not done any test (unit/integration). If there are any acceptance criteria for PR, could you tell me that?

**Comment by k-suga-SD** [comment]
@siddarth09 
Yes, I will try them.
Is visualization of orbit you mean like this? Now I have implemented test materials (main function, CMakeList.txt, mockup) and done git push. I'm making README.txt to instruct to run test. After that, I will make PR again.

<img width="637" height="671" alt="Image" src="https://github.com/user-attachments/assets/0b774a23-9d2b-4783-ac08-923a8fa058fa" />

**Comment by siddarth09** [comment]
@k-suga-SD Yes sir, this is something which I wanted so that it's easier for anybody to understand. Also, our GNC nodes are LVLH frames. Are we converting that to ECI, or will you use the LVLH frame later? Additionally, most of the subscribed topics are incorrect. Please check the GNC nodes to have a better understanding. 
I also noticed a string which asks TLE, can you please help me understand what this is, because we might need to publish this topic by GNC. 


Please use ``feature/57-dynamics`` branch to push your commits, I have refactored some ROS parts for parameter usage too.

**Comment by siddarth09** [comment]
@k-suga-SD thanks a lot for explaining me the concepts. I understand them now. But the topics subscribed are not the same which we are being used in GNC, please check ``physics_motion.cpp`` for more information regarding this.

**Comment by k-suga-SD** [comment]
@siddarth09 I appreciate you refactoring the code.
Are what I should do next those?
- Check `orbit_dynamics.cpp` in the branch `feature/57-dynamics`
- Make PR to merge my test code and visualization code to `feature/57-dynamics`
- Read `physics_motion.cpp` and understand published topics

**Comment by k-suga-SD** [comment]
@siddarth09 
orbit_dynamics install was not in CMakeList.txt, so I made a PR to modify that.
And when I did this in `feature/57-dynamics`,
```
$ colcon build --symlink-install
$ source install/setup.sh
$ ros2 run space_station_gnc orbit_dynamics 
```
This error occured.
```space_station_gnc/tests/orbit_dynamics/params.yaml
[ERROR] [1755436084.935177123] [orbit_dynamics_node]: initial.tle_line2 is empty. Set a valid TLE line 2.
[INFO] [1755436084.938017978] [orbit_dynamics_node]: OrbitDynamicsNode ready. dt=0.250 s, pub=0.500 s, RK4=false
orbit_dynamics: /usr/include/eigen3/Eigen/src/Core/Product.h:96: Eigen::Product<Lhs, Rhs, Option>::Product(const Lhs&, const Rhs&) [with _Lhs = Eigen::Matrix<double, 3, -1>; _Rhs = Eigen::Matrix<double, -1, 1>; int Option = 0; Eigen::Product<Lhs, Rhs, Option>::Lhs = Eigen::Matrix<double, 3, -1>; Eigen::Product<Lhs, Rhs, Option>::Rhs = Eigen::Matrix<double, -1, 1>]: Assertion `lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"' failed.
[ros2run]: Aborted```

**Comment by siddarth09** [comment]
@k-suga-SD I have merged your PR to the feature branch, now you should be able to make changes to your code and test it out

**Comment by k-suga-SD** [comment]
@siddarth09 
I made PR [#134](https://github.com/space-station-os/space_station_os/pull/134). Could you check it?

**Comment by siddarth09** [comment]
@k-suga-SD remove your build and install folder. Then build the entire workspace with 

``bash
colcon build --symlink-install 
``

**Comment by k-suga-SD** [comment]
@siddarth09 
It still doesn't work. When I run `colcon build --symlink-install`, I get a lot of warnings. Could these be the cause?
Sorry for long console output.

```
sugawara@spica:~/ssos_ws $ rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Skip end-of-life distro "foxy"
Skip end-of-life distro "galactic"
Skip end-of-life distro "groovy"
Add distro "humble"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "iron"
Skip end-of-life distro "jade"
Add distro "jazzy"
Add distro "kilted"
Skip end-of-life distro "kinetic"
Skip end-of-life distro "lunar"
Skip end-of-life distro "melodic"
Skip end-of-life distro "noetic"
Add distro "rolling"
updated cache in /home/sugawara/.ros/rosdep/sources.cache

sugawara@spica:~/ssos_ws $ rosdep install --from-paths src --ignore-src -r -y
#All required rosdeps installed successfully

sugawara@spica:~/ssos_ws $ colcon build --symlink-install
[0.454s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/sugawara/ssos_ws/install/space_station_thermal_control' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.455s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/sugawara/ssos_ws/install/space_station_gnc' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.455s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/sugawara/ssos_ws/install/space_station_eclss' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.455s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/sugawara/ssos_ws/install/space_station_description' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.455s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/sugawara/ssos_ws/install/space_station_control' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.455s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/sugawara/ssos_ws/install/space_station_communication' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.457s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/sugawara/ssos_ws/install/space_station_thermal_control' in the environment variable CMAKE_PREFIX_PATH doesn't exist
[0.457s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/sugawara/ssos_ws/install/space_station_gnc' in the environment variable CMAKE_PREFIX_PATH doesn't exist
[0.457s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/sugawara/ssos_ws/install/space_station_eclss' in the environment variable CMAKE_PREFIX_PATH doesn't exist
[0.457s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/sugawara/ssos_ws/install/space_station_control' in the environment variable CMAKE_PREFIX_PATH doesn't exist
Starting >>> space_station_eclss
Starting >>> space_station_communication
Starting >>> space_station_control
Starting >>> space_station_description
Starting >>> space_station_gnc
Finished <<< space_station_description [0.86s]
Finished <<< space_station_communication [0.88s]
--- stderr: space_station_control
CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:38 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:44 (rosidl_target_interfaces)


---
Finished <<< space_station_control [15.7s]
--- stderr: space_station_eclss
CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:51 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:55 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:59 (rosidl_target_interfaces)


/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp: In constructor ‘space_station_eclss::ARSActionServer::ARSActionServer(const rclcpp::NodeOptions&)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp:17:9: warning: typedef ‘using GoalHandleAirRevitalisation = class rclcpp_action::ServerGoalHandle<space_station_eclss::action::AirRevitalisation>’ locally defined but not used [-Wunused-local-typedefs]
   17 |   using GoalHandleAirRevitalisation = rclcpp_action::ServerGoalHandle<AirRevitalisation>;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp: In member function ‘void space_station_eclss::ARSActionServer::execute(std::shared_ptr<rclcpp_action::ServerGoalHandle<space_station_eclss::action::AirRevitalisation> >)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp:116:9: warning: unused variable ‘contaminants’ [-Wunused-variable]
  116 |   float contaminants = goal_handle->get_goal()->initial_contaminants;
      |         ^~~~~~~~~~~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp: In member function ‘bool space_station_eclss::ARSActionServer::simulate_desiccant_bed(float&, float, float, float, const string&, float&)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp:194:64: warning: unused parameter ‘cap’ [-Wunused-parameter]
  194 | bool ARSActionServer::simulate_desiccant_bed(float &h2o, float cap, float rate, float max_temp, const std::string &name, float &temp)
      |                                                          ~~~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp: In member function ‘bool space_station_eclss::ARSActionServer::simulate_adsorbent_bed(float&, float, float, float, const string&, float&)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ars_systems/ars_systems.cpp:207:64: warning: unused parameter ‘cap’ [-Wunused-parameter]
  207 | bool ARSActionServer::simulate_adsorbent_bed(float &co2, float cap, float rate, float max_temp, const std::string &name, float &temp)
      |                                                          ~~~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/wrs_systems/src/wrs_systems.cpp: In member function ‘void space_station_eclss::WRSActionServer::send_water_to_ogs(float, float)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/wrs_systems/src/wrs_systems.cpp:188:61: warning: unused parameter ‘iodine_ppm’ [-Wunused-parameter]
  188 | void WRSActionServer::send_water_to_ogs(float volume, float iodine_ppm)
      |                                                       ~~~~~~^~~~~~~~~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ors_systems/src/ogs_systems.cpp: In member function ‘rclcpp_action::GoalResponse OGSSystem::handle_goal(const GoalUUID&, std::shared_ptr<const space_station_eclss::action::OxygenGeneration_Goal_<std::allocator<void> > >)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_eclss/src/ors_systems/src/ogs_systems.cpp:69:78: warning: unused parameter ‘goal’ [-Wunused-parameter]
   69 |   std::shared_ptr<const space_station_eclss::action::OxygenGeneration::Goal> goal)
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
---
Finished <<< space_station_eclss [23.1s]
Starting >>> space_station_thermal_control
--- stderr: space_station_gnc
In file included from /home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/physics_motion.cpp:23:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘int L_p_func_f0(const double**, double**, long long int*, double*, int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:280:78: warning: unused parameter ‘iw’ [-Wunused-parameter]
  280 | static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
      |                                                                              ^
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:280:102: warning: unused parameter ‘mem’ [-Wunused-parameter]
  280 | static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
      |                                                                                                  ~~~~^~~
In file included from /home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/physics_motion.cpp:23:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘int pseudoInvFunc_init_mem(int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:471:64: warning: unused parameter ‘mem’ [-Wunused-parameter]
  471 | extern "C" CASADI_SYMBOL_EXPORT int pseudoInvFunc_init_mem(int mem) {
      |                                                            ~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘void pseudoInvFunc_free_mem(int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:475:65: warning: unused parameter ‘mem’ [-Wunused-parameter]
  475 | extern "C" CASADI_SYMBOL_EXPORT void pseudoInvFunc_free_mem(int mem) {
      |                                                             ~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘void pseudoInvFunc_release(int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:482:64: warning: unused parameter ‘mem’ [-Wunused-parameter]
  482 | extern "C" CASADI_SYMBOL_EXPORT void pseudoInvFunc_release(int mem) {
      |                                                            ~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘int L_p_func_f1(const double**, double**, long long int*, double*, int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:552:78: warning: unused parameter ‘iw’ [-Wunused-parameter]
  552 | static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
      |                                                                              ^
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:552:102: warning: unused parameter ‘mem’ [-Wunused-parameter]
  552 | static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
      |                                                                                                  ~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘int hFunc_init_mem(int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:667:56: warning: unused parameter ‘mem’ [-Wunused-parameter]
  667 | extern "C" CASADI_SYMBOL_EXPORT int hFunc_init_mem(int mem) {
      |                                                    ~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘void hFunc_free_mem(int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:671:57: warning: unused parameter ‘mem’ [-Wunused-parameter]
  671 | extern "C" CASADI_SYMBOL_EXPORT void hFunc_free_mem(int mem) {
      |                                                     ~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp: In function ‘void hFunc_release(int)’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/L_p_func.cpp:678:56: warning: unused parameter ‘mem’ [-Wunused-parameter]
  678 | extern "C" CASADI_SYMBOL_EXPORT void hFunc_release(int mem) {
      |                                                    ~~~~^~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/control_torque.cpp: In member function ‘void ControlTorque::compute_control()’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/control_torque.cpp:165:21: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘Eigen::EigenBase<Eigen::Matrix<double, -1, 1> >::Index’ {aka ‘long int’} [-Wsign-compare]
  165 |             if (idx != thruster_force.size()) idx++;
      |                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/physics_motion.cpp: In member function ‘tf2::Vector3 AttitudeDynamicsNode::gravityGradT()’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_gnc/src/physics_motion.cpp:604:29: warning: variable ‘yaw’ set but not used [-Wunused-but-set-variable]
  604 |         double roll, pitch, yaw;
      |                             ^~~
---
Finished <<< space_station_gnc [47.0s]
--- stderr: space_station_thermal_control
CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:51 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:55 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:59 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:64 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:71 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:75 (rosidl_target_interfaces)


CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:80 (rosidl_target_interfaces)


In file included from /home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/src/coolant.cpp:1:
/home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/include/space_station_thermal_control/coolant.hpp: In constructor ‘space_station_thermal_control::CoolantManager::CoolantManager()’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/include/space_station_thermal_control/coolant.hpp:83:8: warning: ‘space_station_thermal_control::CoolantManager::water_acquired_’ will be initialized after [-Wreorder]
   83 |   bool water_acquired_;
      |        ^~~~~~~~~~~~~~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/include/space_station_thermal_control/coolant.hpp:67:8: warning:   ‘bool space_station_thermal_control::CoolantManager::water_request_pending_’ [-Wreorder]
   67 |   bool water_request_pending_ = false;
      |        ^~~~~~~~~~~~~~~~~~~~~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/src/coolant.cpp:9:1: warning:   when initialized here [-Wreorder]
    9 | CoolantManager::CoolantManager()
      | ^~~~~~~~~~~~~~
/home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/src/coolant.cpp: In member function ‘void space_station_thermal_control::CoolantManager::request_water()’:
/home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/src/coolant.cpp:69:56: warning: ‘rclcpp::Client<ServiceT>::FutureAndRequestId::operator rclcpp::Client<ServiceT>::SharedFuture() [with ServiceT = space_station_eclss::srv::RequestProductWater; rclcpp::Client<ServiceT>::SharedFuture = std::shared_future<std::shared_ptr<space_station_eclss::srv::RequestProductWater_Response_<std::allocator<void> > > >]’ is deprecated: FutureAndRequestId: use .future.share() instead of an implicit conversion [-Wdeprecated-declarations]
   69 |   water_future_ = water_client_->async_send_request(req);
      |                                                        ^
In file included from /opt/ros/humble/include/rclcpp/rclcpp/callback_group.hpp:24,
                 from /opt/ros/humble/include/rclcpp/rclcpp/any_executable.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor_options.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor.hpp:37,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors.hpp:21,
                 from /opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:155,
                 from /home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/include/space_station_thermal_control/coolant.hpp:4,
                 from /home/sugawara/ssos_ws/src/space_station_os/space_station_thermal_control/src/coolant.cpp:1:
/opt/ros/humble/include/rclcpp/rclcpp/client.hpp:415:5: note: declared here
  415 |     operator SharedFuture() {return this->future.share();}
      |     ^~~~~~~~
---
Finished <<< space_station_thermal_control [31.7s]

Summary: 6 packages finished [55.2s]
  4 packages had stderr output: space_station_control space_station_eclss space_station_gnc space_station_thermal_control

sugawara@spica:~/ssos_ws $ ros2 launch space_station_gnc orbit_dynamics.launch.py
[INFO] [launch]: All log files can be found below /home/sugawara/.ros/log/2025-08-21-23-51-58-677203-spica-334788
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [orbit_dynamics-1]: process started with pid [334789]
[INFO] [orbit_dynamics_mock-2]: process started with pid [334791]
[orbit_dynamics_mock-2] [INFO] [1755787918.783504159] [orbit_dynamics_mock]: OrbitDynamicsMockNode started.
[orbit_dynamics-1] [INFO] [1755787918.786018319] [orbit_dynamics_node]: OrbitDynamicsNode ready. dt=10.000 s, pub=1.000 s, RK4=true
[orbit_dynamics_mock-2] [INFO] [1755787922.541151687] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787922.541229398] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787922.541260710] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787922.541317050] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787923.454300767] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787923.454382891] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787923.454428027] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787923.454532608] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787924.374664971] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787924.374729307] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787924.374746075] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787924.374893220] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787925.294531556] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787925.294602855] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787925.294618218] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787925.294778542] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787926.214524551] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787926.214602311] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787926.214632454] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787926.214721461] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787927.134653198] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787927.134742652] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787927.134779700] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787927.134922627] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787928.054358698] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787928.054435111] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787928.054491814] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787928.054563926] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787928.976730075] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787928.976804198] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787928.976821035] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787928.977001941] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787929.899157115] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787929.899237290] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787929.899270220] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787929.899301643] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787930.821564795] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787930.821637157] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787930.821661433] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787930.821747794] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787931.744168154] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787931.744307944] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787931.744412060] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787931.744568086] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787932.666463737] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787932.666537185] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787932.666602908] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787932.666819469] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787933.588810808] [orbit_dynamics_mock]: Published: gnc/t_fwd_sim
[orbit_dynamics_mock-2] [INFO] [1755787933.588904481] [orbit_dynamics_mock]: Published: gnc/attitude_body_to_eci
[orbit_dynamics_mock-2] [INFO] [1755787933.588933925] [orbit_dynamics_mock]: Published: gnc/bias_thruster_cmd
[orbit_dynamics-1] [INFO] [1755787933.588992921] [orbit_dynamics_node]: Subscribed: gnc/t_fwd_sim
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[orbit_dynamics_mock-2] [INFO] [1755787933.821805733] [rclcpp]: signal_handler(signum=2)
[orbit_dynamics-1] [INFO] [1755787933.821993005] [rclcpp]: signal_handler(signum=2)
[INFO] [orbit_dynamics_mock-2]: process has finished cleanly [pid 334791]
[INFO] [orbit_dynamics-1]: process has finished cleanly [pid 334789]

sugawara@spica:~/ssos_ws $ ros2 run space_station_gnc draw_3d_plot.py
No executable found
```

**Comment by k-suga-SD** [comment]
@siddarth09 
I tried these command,
```
$ cd ~/ssos_ws
$ rm -rf install/ log/ build/
$ chmod +x src/space_station_os/space_station_gnc/scripts/draw_3d_position.py
$ colcon build --symlink-install
$ sudo rosdep init
$ rosdep update
$ rosdep install --from-paths src --ignore-src -r -y
$ source install/setup.sh
$ ros2 launch space_station_gnc orbit_dynamics.launch.py
$ ros2 run space_station_gnc draw_3d_plot.py
```
But `No executable found` appeared again.
Are my commands correct?

And tree structure is like this.
```
src/space_station_os/space_station_gnc/
├── action
│   └── Unloading.action
├── CMakeLists.txt
├── config
│   ├── config.json
│   ├── params.yaml
│   └── ros_config.yaml
├── include
│   └── space_station_gnc
│       ├── orbit_dynamics.hpp
│       └── thruster_matrix.hpp
├── launch
│   ├── gnc_core.launch.py
│   ├── gnc_rviz.launch.py
│   ├── gnc_rviz_thruster.launch.py
│   └── orbit_dynamics.launch.py
├── LICENSE
├── media
│   ├── 001_start.png
│   ├── 100_emergency_begin.png
│   └── 102_emergency_reaction.png
├── package.xml
├── README.md
├── resource
│   └── space_station_gnc
├── rviz
│   └── ssos.rviz
├── scripts
│   ├── draw_3d_position.py
│   └── jacob_cmgs_casadi.py
├── setup.py
├── src
│   ├── control_torque.cpp
│   ├── demo1a_nauka_incident_estimate.cpp
│   ├── demo1b_crisis_mainengine.cpp
│   ├── demo1c_small_incident.cpp
│   ├── demo1d_sitl.cpp
│   ├── L_p_func.cpp
│   ├── orbit_dynamics.cpp
│   ├── orbit_dynamics_mock.cpp
│   ├── physics_motion.cpp
│   ├── physics_sensor.cpp
│   ├── sense_estimate.cpp
│   ├── space_station_gnc.cpp
│   ├── thruster_matrix.cpp
│   └── torque_collector.cpp
├── tests
│   ├── L_p_func.cpp
│   ├── orbit_dynamics
│   │   ├── rosbag_record.sh
│   │   └── rosbag_to_csv.py
│   ├── pseudoinv_executable
│   ├── test_jacob.cpp
│   └── test_quat.cpp
└── urdf
    ├── ISS_stationaryFromNasa.urdf
    ├── meshes
    └── SD_SpaceStation_Ver05.urdf
```
Is path of `draw_3d_position.py` correct?

**Comment by siddarth09** [comment]
@k-suga-SD  I reinstalled, and I was able to run the draw_3d_plot.py. Though all the commands you tried are absolutely correct. Anyway, the previous problem was occurring due to the node not being closed or shut down properly. If you are still facing the issue, remove the entire space_station repo, and clone the feature/57-dynamics branch 


<img width="1000" height="747" alt="Image" src="https://github.com/user-attachments/assets/343c8e13-a17d-45e0-82ed-1ad325272ab2" />

**Comment by k-suga-SD** [comment]
@siddarth09 @snktshrma @yuyuqq 
In the latest version of the branch "feature/57-dynamics", only gravity effect is considered in orbit dynamics. So I added J2 and air drag effect. I have not made PR yet.

I did those commands, but no message or plot appears after `ros2 run space_station_gnc draw_3d_position.py`. Are there any mistakes?
```
$ cd ~/ssos_ws
$ rm -rf install/ log/ build/
$ chmod +x src/space_station_os/space_station_gnc/scripts/draw_3d_position.py
$ colcon build --symlink-install
$ sudo rosdep init
$ rosdep update
$ rosdep install --from-paths src --ignore-src -r -y
$ source install/setup.sh
$ ros2 launch space_station_gnc orbit_dynamics.launch.py
$ ros2 run space_station_gnc draw_3d_position.py
```

**Comment by siddarth09** [comment]
@k-suga-SD 

Let me know if you made a commit, the ``draw_3d_position.py`` is opening in my PC. Let me try changing the code to show a simpler visualisation.

**Comment by k-suga-SD** [comment]
@siddarth09 
I'm sorry, but I made a mistake. I ran these commands in one terminal.
```
$ ros2 launch space_station_gnc orbit_dynamics.launch.py
$ ros2 run space_station_gnc draw_3d_position.py
```
To run correctly, two terminals are required. I finally realized that.

**Comment by siddarth09** [comment]
@k-suga-SD Let us know if the orbital dynamics are ready for integration into v0.8.6-dev

**Comment by k-suga-SD** [comment]
@siddarth09  Now they are ready for integration into v0.8.6-dev.
